---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "salmon-fabric"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "Salmon Network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see org1.yaml and org2.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  fredrick-alice:
    orderers:
      - orderer.coderschool.vn

    # Required. list of peers from participating orgs
    peers:
      peer0.fredrick.coderschool.vn:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.alice.coderschool.vn:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - salmon_price_cc:v0

  # name of the channel
  fredrick-bob:
    orderers:
      - orderer.coderschool.vn

    # Required. list of peers from participating orgs
    peers:
      peer0.fredrick.coderschool.vn:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.bob.coderschool.vn:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - salmon_price_cc:v0
#
# list of participating organizations in this network
#
organizations:
  Fredrick:
    mspid: FredrickMSP

    peers:
      - peer0.fredrick.coderschool.vn

    certificateAuthorities:
      - ca-fredrick

    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/fredrick.coderschool.vn/users/Admin@fredrick.coderschool.vn/msp/keystore/key.pem
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/fredrick.coderschool.vn/users/Admin@fredrick.coderschool.vn/msp/signcerts/Admin@fredrick.coderschool.vn-cert.pem

  Alice:
    mspid: AliceMSP

    peers:
      - peer0.alice.coderschool.vn

    certificateAuthorities:
      - ca-alice

    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/alice.coderschool.vn/users/Admin@alice.coderschool.vn/msp/keystore/key.pem
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/alice.coderschool.vn/users/Admin@alice.coderschool.vn/msp/signcerts/Admin@alice.coderschool.vn-cert.pem

  Bob:
    mspid: BobMSP

    peers:
      - peer0.bob.coderschool.vn

    certificateAuthorities:
      - ca-bob

    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/bob.coderschool.vn/users/Admin@bob.coderschool.vn/msp/keystore/key.pem
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/bob.coderschool.vn/users/Admin@bob.coderschool.vn/msp/signcerts/Admin@bob.coderschool.vn-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.coderschool.vn:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.coderschool.vn
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: artifacts/channel/crypto-config/ordererOrganizations/coderschool.vn/orderers/orderer.coderschool.vn/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.fredrick.coderschool.vn:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:7053

    grpcOptions:
      ssl-target-name-override: peer0.fredrick.coderschool.vn
    tlsCACerts:
      path: crypto-config/peerOrganizations/fredrick.coderschool.vn/peers/peer0.fredrick.coderschool.vn/tls/ca.crt

  peer0.alice.coderschool.vn:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:7053

    grpcOptions:
      ssl-target-name-override: peer0.alice.coderschool.vn
    tlsCACerts:
      path: crypto-config/peerOrganizations/alice.coderschool.vn/peers/peer0.alice.coderschool.vn/tls/ca.crt

  peer0.bob.coderschool.vn:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:7053

    grpcOptions:
      ssl-target-name-override: peer0.bob.coderschool.vn
    tlsCACerts:
      path: crypto-config/peerOrganizations/bob.coderschool.vn/peers/peer0.bob.coderschool.vn/tls/ca.crt

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-fredrick:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/fredrick.coderschool.vn/ca/ca.fredrick.coderschool.vn-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-fredrick

  ca-alice:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/alice.coderschool.vn/ca/ca.alice.coderschool.vn-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-alice

  ca-bob:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/bob.coderschool.vn/ca/ca.bob.coderschool.vn-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-bob
